export const PENDING_LABEL = "@PENDING_LABEL";
export const FAILURE_LABEL = "@FAILURE_LABEL";

export const PENDING_MEMO = "@PENDING_MEMO";
export const FAILURE_MEMO = "@FAILURE_MEMO";

export const FETCH_ALL_LABELS = "@FETCH_ALL_LABELS";
export const FETCH_ALL_MEMOS = "@FETCH_ALL_MEMOS";

export const FETCH_LABEL = "@FETCH_LABEL";
export const CREATE_LABEL = "@CREATE_LABEL";
export const UPDATE_LABEL = "@UPDATE_LABEL";
export const DELETE_LABEL = "@DELETE_LABEL";

export const FETCH_MEMOS_BY_LABEL = "@FETCH_MEMOS_BY_LABEL";
export const CREATE_MEMO = "@CREATE_MEMO";
export const UPDATE_MEMO = "@UPDATE_MEMO";
export const DELETE_MEMO = "@DELETE_MEMO";

export const REGISTER_MEMO_TO_LABEL = "@REGISTER_MEMO_TO_LABEL";
export const DEREGISTER_MEMO_TO_LABEL = "@DEREGISTER_MEMO_TO_LABEL";
